FROM ubuntu:18.04@sha256:369d14bd01c8ad4c81698d2f4605509a9985da47b51206c612ebb49191c0eddd
LABEL xwzhu="xwzhu7@iflytek.com"
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /home

RUN apt-get update
RUN apt-get install jq -y
